import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { getImage } from "@/components/utils";

export default function Home() {
  const [chosen, setChosen] = useState(0);

  const handleClick = () => {
    const val = Math.ceil(Math.random() * 4);
    setChosen(val);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.description}>
            <h1 className={styles.title}>Cześć Tosia!</h1>
          </div>
        </div>

        <button className={styles.button} onClick={handleClick}>
          Losowanie
        </button>

        <div>
          {chosen > 0 && (
            <Image src={getImage(chosen)} alt="me" width="128" height="128" />
          )}
        </div>
      </main>
    </>
  );
}
