import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { getImage } from "@/components/utils";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [chosen, setChosen] = useState(0);
  const handleClick = () => {
    const val = Math.ceil(Math.random() * 4);
    console.log("val", val);
    setChosen(val);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.description}>
            <h1 className={styles.title}>Cześć Tosia!</h1>
          </div>
        </div>

        <button className={styles.title} onClick={handleClick}>
          Losowanie
        </button>

        {chosen ? (
          <div>
            <Image src={getImage(chosen)} alt="me" width="128" height="128" />
          </div>
        ) : (
          <></>
        )}
      </main>
    </>
  );
}
